num_instances = 100
seed = 1
search_timeout_ms = 10000
search_max_iterations = 50
search_repetitions = 2

[vass_counters]
min = 2
max = 3

[vass_states]
min = 2
max = 6

[vass_transitions]
min = 4
max = 12

[vass_updates]
min = -3
max = 3

[vass_valuations]
min = 0
max = 3
