[package]
name = "vass-reach"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.47", features = ["derive"] }
vass-reach-lib = { path = "../vass-reach-lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"